### ISSUE TITLE
Motivation links are gone

### ISSUE THREAD

**Issue by YouGotHitByGunner** [labrocadabro/communitytaught#13]
After the re-design, I noticed that the motivation links are gone. Which is something I love looking at. Are you planning on re-adding them at some point? Thanks in advance!

**Comment by labrocadabro** [comment]
Oh I'm so sorry! that was a complete oversight on my part, thank you for bringing it to my attention. will get it fixed ASAP.

**Comment by labrocadabro** [comment]
Fixed. :)
