### ISSUE TITLE
Class 19 Correct Homework Google Form

### ISSUE THREAD

**Issue by d-perez-8** [labrocadabro/communitytaught#15]
The submission form from class 19 is different than the linked form listed. I suggest changing the link so the homework submissions for the portfolio and proposal/contract drafts can be sent to the correct google form.

- The link that was on Leon's slides: https://forms.gle/PLuuSi7aHeL7wbMQ9
- The link listed on community taught: https://forms.gle/q9qvPkrH5jKgEfxBA

Even though they both are titled class 16, the contents of what you're sending are different.

**Comment by labrocadabro** [comment]
Thanks so much for pointing that out! Somehow I duplicated the submit link from the previous class.

All fixed now :)

**Comment by d-perez-8** [comment]
No problem. I'm happy to help out 😊
