### ISSUE TITLE
Unsure of how to populate Lessons database for local development

### ISSUE THREAD

**Issue by 7MinutesDead-Git** [labrocadabro/communitytaught#17]
Hey there! I'm wanting to contribute and help build some of this site out (like the progress bar), however I haven't been able to figure out how I can populate my local database with the base lessons that are present on the official site/db. I'm not seeing this data anywhere, nor a means of importing it (I see I can import my progress from the old site, but that doesn't give me the base data of each lesson).

When I get everything up and running, the collections are created in the database, but they're empty.
![image](https://user-images.githubusercontent.com/50963144/219168439-4378acd6-4a47-4239-bf2f-e9b963b8830c.png)  
  
So I believe I'm missing all the Lesson data as far as lessons containing videoId, title, thumbnail, etc.
![image](https://user-images.githubusercontent.com/50963144/219168860-2e3cfa67-6fda-452f-93bf-a9749cb6eb2c.png)
  
How can I get my local db populated with the base Lesson documents so I can start developing and testing changes?

**Comment by labrocadabro** [comment]
I apologize, I'm in the middle of a major refactor and haven't got the project fully set up for contributions yet.

I'll get you the lesson and homework json files shortly, you can import them to get the data.

**Comment by labrocadabro** [comment]
The json files are now available in the /data folder, you can import them into their respective collections. 

You'll also need to set up your .env file and add a user. If you run into any issues with that, let me know.

**Comment by 7MinutesDead-Git** [comment]
I appreciate it! I did manage to get the .env setup, I just ran into a bit of a block without the lessons :P
