### ISSUE TITLE
Networking Google Spreadsheet Missing

### ISSUE THREAD

**Issue by diathekez** [labrocadabro/communitytaught#2]
I'll be brief. In the slides for this lesson, Leon puts the link to the spreadsheet we're supposed to use/have used.

https://communitytaught.org/class/networking-night

But it's not listed on the homework. Here's the link to the sheet: https://docs.google.com/spreadsheets/d/1Be-6gYvrfi8l-M0RnObzdysRIG7N7Yyu6rIF0OHw0Q4/edit#gid=1771441293

Thanks!

**Comment by labrocadabro** [comment]
Thanks for this! For now, I've added a note at the top the video that links to the sheet, but I'll double check the homework for the lesson and see if I missed an assignment.
