### ISSUE TITLE
Server timeout

### ISSUE THREAD

**Issue by AitchGrasso** [labrocadabro/communitytaught#23]
Hello! 

Here to report community taught being down and server timeout.
Please let me know if there are any ways I can assist :)

Thank you!
H

![image](https://user-images.githubusercontent.com/119631464/228578797-cfbac54e-5b7a-49a4-957a-4e01377733f3.png)

**Comment by labrocadabro** [comment]
Stability issue with the MongoDB cluster, seems to be resolved now!
