### ISSUE TITLE
Classes not being greyed out when marked as watched

### ISSUE THREAD

**Issue by eleanorlatus** [labrocadabro/communitytaught#24]
Classes that do not have a check-in are not greyed out when marked watched. If you uncheck and re-check the watched box, it becomes greyed out but does not save on refresh. Assume this is due to check-in being set as false as default if there is no check in link. It makes it look like there are more classes to watch than there actually are.

<img width="1280" alt="image" src="https://github.com/labrocadabro/communitytaught/assets/90465357/cea233b0-571b-4ffc-a67d-3f8b1942ff43">

**Comment by portfedh** [comment]
Experiencing the same Issue.

**Comment by labrocadabro** [comment]
So sorry for the delay in getting to this. I *thought* I had taken this into account - not sure if I'm misremembering or I broke something somewhere along the way. Leaving this open for a few days to see if anyone wants to claim it, otherwise I'll tackle it myself.
