### ISSUE TITLE
Missing language attribute

### ISSUE THREAD

**Issue by distriss** [labrocadabro/communitytaught#28]
Add a lang attribute to the html element across the different pages.

**Comment by labrocadabro** [comment]
Thanks for catching this! Would you like to submit a PR?

**Comment by renners7777** [comment]
I'd be happy to deal with this issue to start with.

**Comment by distriss** [comment]
Sure, fine by me! Let me know if you have any issues with it.

**Comment by labrocadabro** [comment]
Alright then, I've assigned you to the issue. :) When submitting a PR, please link it to this issue:
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by renners7777** [comment]
Pull request added
