### ISSUE TITLE
Add temporary note and workaround for inaccessible video

### ISSUE THREAD

**Issue by intelagense** [labrocadabro/communitytaught#31]
## Description

Since the first video is still unavailable, we can temporarily link the video from class 01 with notes on the differences and a short explanation.

### Steps:
- Add a clear message on the page where the first video was. Let students know we're using an older video temporarily.
- Include a disclaimer in the message saying that the original video's removal is under dispute, and we're not certain who made the claim as that is also under dispute.
- Link the video from our older cohort 01 series. Make sure to explain that it's from an earlier series and there may be some differences in content.
- Emphasize that the main goal is to start working on the 'Learning to Learn' course homework.
- Also, let's link to Leon's Twitter post that explains the situation for students who want more context on this issue.

### Notes:
We should also be ready to quickly revert this change as soon as the video is restored with a follow up note that it is now working. 

🙋 I am willing to take on this issue if you would like to assign it to me.

**Comment by labrocadabro** [comment]
I'm just getting back into doing some work on the site, and this is one of the tasks I need to do. It would be fantastic if you could take this on! I think it would be best to add a callout on the existing page to a new page that fully details the current situation. Then when the situation is resolved, we can simply remove the callout. 

The task will need:
1) A new page created with the necessary information.
2) A new route added.
3) The code for the callout, which I'll insert into the DB.  You can use the classes "flash flash-error" to use the existing red callout style.

**Comment by intelagense** [comment]
SGTM

I can get started on it within the next hour. 👍
