### ISSUE TITLE
'Watched' labels not correctly linked to their checkboxes

### ISSUE THREAD

**Issue by labrocadabro** [labrocadabro/communitytaught#32]
The issue should be in lessonCard.pug. On the class listing page https://communitytaught.org/class/all and on the dashboard, clicking on the 'watched' labels does not cause their corresponding checkboxes to become checked.

**Comment by numulaa** [comment]
please assign me this issue :)

**Comment by labrocadabro** [comment]
Done! :)

**Comment by numulaa** [comment]
ok. So it means, when we check the "watched" checkbox, the "checked in" checkbox should be checked as well?

**Comment by labrocadabro** [comment]
Not quite. When you click on the text associated with a checkbox, it should cause the checkbox to check/uncheck, like if you clicked on the checkbox itself. The 'checked in' label works correctly, but the 'watched' one doesn't.

Here's a video showing the issue:

https://github.com/labrocadabro/communitytaught/assets/5794319/1d55e2cd-5993-4d2e-ad0a-5873f9d7ff89

**Comment by numulaa** [comment]
ok, i got it. thank you, laura
