### ISSUE TITLE
[UX] Updated styling across site

### ISSUE THREAD

**Issue by coltonehrman** [labrocadabro/communitytaught#46]
I know styling is a personal preference, but IMO, the current styling feels a little wonky and could use some improvement :)

A couple items I would start with:
1. Set a max-width (ie: 1200px) for the content boundaries, as to not expand with huge screen sizes.
2. Replace the landing page image with something more community based.
3. Clear color palette for common tags across site.
   - Links/buttons should match
   - Pure text colors shouldn't be confused with link colors.
   - Reduce the tech overhead of colors being applies in different places
4. Cleaner & more modern card components. The cards feel *outdated*.

**Comment by labrocadabro** [comment]
I agree, the styling needs work. And I also agree with everything you're saying. But as I said before, I'm not sure how much longer this current design will be in use. I don't see a reason to invest time in it until we know how long it will live. So I'd like to put a pin in this for just a couple of days; I will update you as soon as I have more information.

As previously mentioned, we can do max-width (@ 2xl) and a new landing page image immediately. If you'd like to put in a PR for those, I'll merge them immediately.

**Comment by labrocadabro** [comment]
An update, as promised: community taught has been semi-official for a while now, but it's now going to be integrated into the 100Devs website. I'm not 100% sure what that will entail, but one of the tasks will be making the design consistent with the main website. Until I know exactly what that will entail, there won't be any design changes.
