### ISSUE TITLE
Mobile menu doesn't show correctly

### ISSUE THREAD

**Issue by victoriacheng15** [labrocadabro/communitytaught#5]
The warning box is blocking the menu
![image](https://user-images.githubusercontent.com/35031228/204641373-f486adb7-1934-4203-a315-9dd8af439391.png)

The same as above
![image](https://user-images.githubusercontent.com/35031228/204641387-26246d10-a386-4ede-a771-039c1c65ffbb.png)

The `resources` title is disappeared after click the hamburger menu
![image](https://user-images.githubusercontent.com/35031228/204641396-572b9e3c-ec08-47a1-ac0c-3694e1698797.png)

**Comment by labrocadabro** [comment]
Hi thank you so much for pointing the out! It seems I introduced a bug with a recent update but I've squashed it (I think!). Please let me know if you're still having issues.

**Comment by victoriacheng15** [comment]
> Hi thank you so much for pointing the out! It seems I introduced a bug with a recent update but I've squashed it (I think!). Please let me know if you're still having issues.

@labrocadabro Thank you for the fast fix! So far, it looks great now! Definitely will let you know if I find anything! 👍
