### ISSUE TITLE
Update Mayanwolfe twitch links to youtube

### ISSUE THREAD

**Issue by Nam-Nguyen-Dev** [labrocadabro/communitytaught#6]
Class 57-60 EXTRAS references Part 1 and Part 2 of Mayanwolfe's walkthrough of React.

The link to the Twitch VOD's are no longer available but Mayanwolfe does have them available on Youtube.

Please update the links to:

Part 1: https://www.youtube.com/watch?v=MFEmmHEm6nk
Part 2: https://www.youtube.com/watch?v=xzVggz2XJy4

Thanks for all your hard work!

**Comment by labrocadabro** [comment]
Thank you for reminding me! They've been updated. :)
