### ISSUE TITLE
Repo about section

### ISSUE THREAD

**Issue by nmpereira** [labrocadabro/communitytaught#62]
The repo about section could use some information like the link to the app, description etc

<img width="611" alt="image" src="https://github.com/labrocadabro/communitytaught/assets/45009203/05bba30d-8ab9-4882-a915-ed624ac4cfe9">

**Comment by labrocadabro** [comment]
Thanks for pointing that out. Probably won't bother here as this will be archived soon. I'll do better on the next repo, I promise.
