### ISSUE TITLE
Collapse Rows?

### ISSUE THREAD

**Issue by namastegeek** [labrocadabro/communitytaught#7]
Would it work to allow users to collapse rows on the Homework page? Individually or in small groups (5, 10, etc.)? This could work for the table on the Classes page too, but since it is likely not used as much...not a big deal. Being able to toggle rows closed would save some scrolling.

If there is a better way that already exists, I am open to hearing about it. 

Either way, thank you!

**Comment by labrocadabro** [comment]
Thanks for the feedback! I'm actually in the process of reworking the class and homework pages and one of the things i'll be doing is creating two tabs, Incomplete and Complete. That will get the old completed homework out of the way so the most recent assignments are on top.

I'm also considering adding the option to collapse rows for the situation where someone hasn't completed everything yet but has moved on to newer homework & plans to go back and finish old work later.

**Comment by labrocadabro** [comment]
Well it's a year later and I *still* haven't done this! Leaving it open for a bit to see if anyone would like to work on it.

**Comment by labrocadabro** [comment]
Closing this issue, to be replaced with two separate ones.
